"use client";
import { useEffect, useState } from "react";
import { CheckCircle2, Send, Unplug } from "lucide-react";

type Connection={teamName:string;channelName:string;updatedAt:string};
export function SlackConnectionPanel(){
 const [connection,setConnection]=useState<Connection|null>(null);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");
 useEffect(()=>{fetch("/api/slack/connection").then(r=>r.json()).then(data=>setConnection(data.connection??null)).catch(()=>setMessage("Impossible de charger la connexion Slack.")).finally(()=>setLoading(false))},[]);
 async function test(){setBusy(true);setMessage("");try{const r=await fetch("/api/slack/connection",{method:"POST"});const data=await r.json();if(!r.ok)throw new Error(data.error);setMessage("Message de test envoyé dans Slack.")}catch(e){setMessage(e instanceof Error?e.message:"Test impossible")}finally{setBusy(false)}}
 async function disconnect(){if(!confirm("Déconnecter Slack de ton compte JobPulse ?"))return;setBusy(true);try{const r=await fetch("/api/slack/connection",{method:"DELETE"});if(!r.ok)throw new Error("Déconnexion impossible");setConnection(null);setMessage("Slack a été déconnecté.")}catch(e){setMessage(e instanceof Error?e.message:"Déconnexion impossible")}finally{setBusy(false)}}
 if(loading)return <div className="slackCard">Chargement…</div>;
 return <div className="slackCard">{connection?<><div className="connectionStatus"><CheckCircle2 size={27}/><div><strong>Slack connecté</strong><span>{connection.teamName} · #{connection.channelName.replace(/^#/,"")}</span></div></div><div className="slackInfo"><span>Espace de travail<strong>{connection.teamName}</strong></span><span>Canal d’alertes<strong>#{connection.channelName.replace(/^#/,"")}</strong></span><span>Protection<strong>Webhook chiffré</strong></span></div><div className="slackActions"><button onClick={test} disabled={busy}><Send size={16}/>Envoyer un test</button><a href="/api/slack/connect">Changer de canal</a><button className="disconnect" onClick={disconnect} disabled={busy}><Unplug size={16}/>Déconnecter</button></div></>:<><div className="notConnected"><span className="slackGlyph small">✣</span><div><h2>Connecte ton espace Slack</h2><p>Slack affichera un sélecteur pour choisir précisément le canal d’alertes. JobPulse demande uniquement la permission d’y publier.</p></div></div><a className="connectSlackButton" href="/api/slack/connect">✣ Ajouter JobPulse à Slack</a></>}{message&&<p className="slackMessage">{message}</p>}<div className="privacyNote"><strong>Confidentialité</strong><p>L’adresse du webhook est chiffrée avant d’être enregistrée. Elle n’est jamais envoyée au navigateur ni affichée dans ton compte.</p></div></div>
}
