"use client";
import { ChangeEvent, useEffect, useRef, useState } from "react";
import { CheckCircle2, FileText, Trash2, Upload } from "lucide-react";

type CvInfo={fileName:string;fileSize:number;pageCount:number;textLength:number;updatedAt?:string};
export function CvUpload(){
 const [cv,setCv]=useState<CvInfo|null>(null);const [status,setStatus]=useState<"loading"|"ready"|"uploading"|"error">("loading");const [message,setMessage]=useState("");const input=useRef<HTMLInputElement>(null);
 useEffect(()=>{fetch("/api/cv").then(async r=>{const data=await r.json();if(!r.ok)throw new Error(data.error);setCv(data.cv??null);setStatus("ready")}).catch(e=>{setMessage(e instanceof Error?e.message:"Chargement impossible");setStatus("error")})},[]);
 async function upload(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];if(!file)return;setStatus("uploading");setMessage("");const form=new FormData();form.append("cv",file);try{const r=await fetch("/api/cv",{method:"POST",body:form});const data=await r.json();if(!r.ok)throw new Error(data.error);setCv(data.cv);setMessage(data.detectedSkills?.length?`CV analysé. Compétences détectées : ${data.detectedSkills.slice(0,8).join(", ")}.`:"CV analysé et enregistré.");setStatus("ready")}catch(e){setMessage(e instanceof Error?e.message:"Import impossible");setStatus("error")}finally{if(input.current)input.current.value=""}}
 async function remove(){if(!confirm("Supprimer le CV et son texte extrait ?"))return;setStatus("uploading");try{const r=await fetch("/api/cv",{method:"DELETE"});if(!r.ok)throw new Error("Suppression impossible");setCv(null);setMessage("CV supprimé définitivement.");setStatus("ready")}catch(e){setMessage(e instanceof Error?e.message:"Suppression impossible");setStatus("error")}}
 return <section className="cvCard"><div className="cvHeading"><span><FileText size={20}/></span><div><h2>Mon CV</h2><p>Il améliore le score et personnalise les textes de candidature.</p></div></div>{status==="loading"?<p className="cvMessage">Chargement…</p>:cv?<div className="cvReady"><CheckCircle2 size={22}/><div><strong>{cv.fileName}</strong><small>{cv.pageCount} page{cv.pageCount>1?"s":""} · {(cv.fileSize/1024).toFixed(0)} Ko · texte extrait</small></div><button onClick={()=>input.current?.click()} disabled={status==="uploading"}>Remplacer</button><button className="cvDelete" onClick={remove} disabled={status==="uploading"} aria-label="Supprimer le CV"><Trash2 size={16}/></button></div>:<button className="cvDrop" onClick={()=>input.current?.click()} disabled={status==="uploading"}><Upload size={20}/><span><strong>{status==="uploading"?"Analyse en cours…":"Importer mon CV"}</strong><small>PDF texte uniquement · 3 Mo maximum · 12 pages maximum</small></span></button>}<input ref={input} className="cvInput" type="file" accept="application/pdf,.pdf" onChange={upload}/>{message&&<p className={`cvMessage ${status}`}>{message}</p>}<p className="cvPrivacy">Le PDF original n’est pas conservé. Son texte est chiffré et supprimable à tout moment.</p></section>
}
