"use client";
import { FormEvent, useEffect, useState } from "react";
import { CheckCircle2, KeyRound, ShieldCheck, Trash2 } from "lucide-react";

type Settings={provider:string;model:string;lastFour:string;updatedAt:string};
export function AiSettingsPanel(){
 const [settings,setSettings]=useState<Settings|null>(null);const [apiKey,setApiKey]=useState("");const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");
 useEffect(()=>{fetch("/api/ai/settings").then(async r=>{const data=await r.json();if(!r.ok)throw new Error(data.error);setSettings(data.settings??null)}).catch(e=>setMessage(e instanceof Error?e.message:"Chargement impossible")).finally(()=>setLoading(false))},[]);
 async function save(event:FormEvent){event.preventDefault();setBusy(true);setMessage("");try{const r=await fetch("/api/ai/settings",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({apiKey})});const data=await r.json();if(!r.ok)throw new Error(data.error);setSettings(data.settings);setApiKey("");setMessage("Clé vérifiée et enregistrée.")}catch(e){setMessage(e instanceof Error?e.message:"Enregistrement impossible")}finally{setBusy(false)}}
 async function remove(){if(!confirm("Supprimer ta clé Gemini de JobPulse ?"))return;setBusy(true);setMessage("");try{const r=await fetch("/api/ai/settings",{method:"DELETE"});if(!r.ok)throw new Error("Suppression impossible");setSettings(null);setMessage("Clé supprimée.")}catch(e){setMessage(e instanceof Error?e.message:"Suppression impossible")}finally{setBusy(false)}}
 if(loading)return <div className="aiCard">Chargement…</div>;
 return <div className="aiCard">{settings?<><div className="aiStatus"><CheckCircle2 size={27}/><div><strong>Gemini est prêt</strong><span>Clé terminant par •••• {settings.lastFour}</span></div></div><div className="aiInfo"><span>Fournisseur<strong>Google Gemini</strong></span><span>Modèle<strong>Gemini 3 Flash</strong></span><span>Stockage<strong>Chiffré AES-256-GCM</strong></span></div><form onSubmit={save} className="aiForm"><label>Remplacer la clé<input type="password" autoComplete="off" value={apiKey} onChange={e=>setApiKey(e.target.value)} placeholder="Colle une nouvelle clé Gemini"/></label><button disabled={busy||apiKey.trim().length<20}>{busy?"Vérification…":"Remplacer"}</button></form><button className="deleteKey" onClick={remove} disabled={busy}><Trash2 size={16}/>Supprimer ma clé</button></>:<><div className="aiIntro"><KeyRound size={28}/><div><h2>Connecte ta clé Gemini</h2><p>Crée gratuitement une clé dans Google AI Studio, puis colle-la ici. Elle sera vérifiée avant son enregistrement.</p></div></div><a className="studioLink" href="https://aistudio.google.com/app/apikey" target="_blank" rel="noreferrer">Créer une clé dans Google AI Studio ↗</a><form onSubmit={save} className="aiForm"><label>Clé API Gemini<input type="password" autoComplete="off" value={apiKey} onChange={e=>setApiKey(e.target.value)} placeholder="Colle ta clé ici" required/></label><button disabled={busy||apiKey.trim().length<20}>{busy?"Vérification…":"Vérifier et enregistrer"}</button></form></>}{message&&<p className="aiMessage">{message}</p>}<div className="aiPrivacy"><ShieldCheck size={18}/><div><strong>Ta clé reste privée</strong><p>Elle est chiffrée avant stockage, utilisée seulement côté serveur et supprimable à tout moment. Les générations consomment uniquement ton quota Gemini.</p></div></div></div>
}
